# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup node.js and yarn 
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Export .env
        run: |
          touch .env.production
          echo ${{secrets.REACT_APP_AWS_IDENTITY_POOL}} >> .env.production
          echo ${{secrets.REACT_APP_AWS_REGION}} >> .env.production
          echo ${{secrets.REACT_APP_AWS_IDENTITY_POOL_REGION}} >> .env.production
          echo ${{secrets.REACT_APP_AWS_USER_POOL_ID}} >> .env.production
          echo ${{secrets.REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID}} >> .env.production
          echo ${{secrets.REACT_APP_OAUTH_DOMAIN}} >> .env.production
          echo ${{secrets.REACT_APP_REDIRECT_URL}} >> .env.production
          echo ${{secrets.REACT_APP_HOST_API_KEY}} >> .env.production
        working-directory: ./

      - name: Build
        run: |
          yarn
          yarn run build
          rm -r node_modules
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Deploy to S3
        run: aws s3 sync ./build s3://portal-service/ --acl public-read
        
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2QAJNDDJKVNB --path "/*"
