# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clear useless artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '14 days'

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Export .env.production file
        run: |
          touch .env.production
        working-directory: ./

      - run: |
          yarn
          yarn run build
          rm -r node_modules

      - uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - uses: actions/download-artifact@v2
        with:
          name: frontend
          path: build

      - run: aws s3 sync ./build s3://portal-service/ --acl public-read
